version: "3"

services:
  db:
    image: mysql:8.0
    cap_add:
    - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=testing
      - MYSQL_ROOT_PASSWORD=basicpassword
    networks:
      - customNetwork
    ports:
      - "3308:3306"
    volumes:
     - db:/var/lib/mysql
     - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
  website:
    image: nextjs-dev
    container_name: nextjs
    build: .
    depends_on:
      - db
    expose:
     - "80"
    environment:
      NODE_ENV: development
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: basicpassword
      DB_NAME: testing
    links:
      - db
    networks:
      - customNetwork 
    volumes:
      - ./:/src
  website2:
    image: nextjs-dev
    container_name: nextjs2
    build: .
    depends_on:
      - db
    expose:
     - "80"
    environment:
      NODE_ENV: development
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: basicpassword
      DB_NAME: testing
    links:
      - db
    networks:
      - customNetwork 
    volumes:
      - ./:/src    
  nginx:
    image: nginx:latest
    container_name: production_nginx
    volumes:
      - ../nginx/reverse_proxy.conf:/etc/nginx/conf.d/default.conf
      - /home/vboxuser/certs/admin.pem:/etc/nginx/cert/admin.pem
      - /home/vboxuser/certs/admin-key.pem:/etc/nginx/cert/admin-key.pem
    ports:
      - "8888:443"
    links:
     - website    
    networks:
      - customNetwork
volumes:
  db:
    driver: local
networks:
    customNetwork:
      name: mynetwork
      driver: bridge