apiVersion: v1
kind: Service
metadata:
  name: db-service
spec:
  selector:
    app: my-db
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
spec:
  storageClassName: whatever
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /var/lib/mysql

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  storageClassName: whatever
  resources:
    requests:
      storage: 10Mi
  accessModes:
    - ReadWriteOnce
  volumeName: mysql-pv

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-db
  template:
    metadata:
      labels:
        app: my-db
    spec:
      restartPolicy: Always
      containers:
        - name: db
          image: mysql:8.0
          securityContext:
            privileged: true
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_DATABASE
              value: "testing"
            - name: MYSQL_ROOT_PASSWORD
              value: "basicpassword"  
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
            #- mountPath: /var/lib/mysql
            #  name: mysql
            #- mountPath: /docker-entrypoint-initdb.d
            #  name: mysql-initdb
            
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: mysql-pvc 
