version: "3"

services:
  db:
    image: mysql:8.0
    cap_add:
    - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=testing
      - MYSQL_ROOT_PASSWORD=basicpassword
    ports:
      - "127.0.0.1:3308:3306"
    volumes:
     - db:/var/lib/mysql
     - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
  api:
    image: nextjs-dev
    container_name: nextjs
    build: .
    depends_on:
      - db
    ports:
      - 8888:80
    environment:
      NODE_ENV: development
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: basicpassword
      DB_NAME: testing
    links:
      - db
    volumes:
      - ./:/src
volumes:
  db:
    driver: local