replicaCount: 1


image:
  repository: public.ecr.aws/z0z3i0h3/myrepo
  tag: latest


resources:
  requests:
    memory: "250Mi"
    cpu: "250m"
  limits:
    memory: "500Mi"  
    cpu: "500m"

ports: 
 containerPort: 80


db_host: "lj-db.cmodmi29ghkz.us-east-2.rds.amazonaws.com"


