apiVersion: apps/v1
kind: Deployment
metadata:
  name: website
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: my-web
  template:
    metadata:
      labels:
        app: my-web
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          resources:
            requests:
              memory: {{ .Values.resources.requests.memory }}
              cpu: {{ .Values.resources.requests.cpu }}
            limits:
              memory: {{ .Values.resources.limits.memory }}
              cpu: {{ .Values.resources.limits.cpu }}
          ports:
            - containerPort: {{ .Values.ports.containerPort }}
          env:
            - name: NODE_ENV
              value: "development"
            - name: DB_HOST
              value: {{ .Values.db_host }}
            - name: DB_PORT
              value: "3306"
            - name: DB_USER
              value: "root"
            - name: DB_PASSWORD
              value: "basicpassword"
            - name: DB_NAME
              value: "testing"
