apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
  selector:
    app: my-web
  ports:
    - protocol: TCP
      port: {{ .Values.ports.containerPort }}
      targetPort: {{ .Values.ports.containerPort }}
